// Generated by CoffeeScript 1.3.1
(function() {
  var csv, exec, fs, yaml;

  yaml = require('js-yaml');

  fs = require('fs');

  csv = require('csv');

  exec = require('child_process').exec;

  exports.run = function() {
    var config, obj;
    config = yaml.load(fs.readFileSync('.googcms.yml'));
    obj = {};
    return exec('google docs get ' + config.document + ' strings.csv', function(err, stdout, stderr) {
      err && (function() {
        throw err;
      })();
      console.log(stdout);
      return csv().from('strings.csv').on('record', function(d, i) {
        if (!(i === 0 || d[0] === '')) {
          return obj[d[config.column_key]] = d[config.column_value];
        }
      }).on('end', function() {
        return fs.writeFile('strings.json', JSON.stringify(obj), function(err) {
          err && (function() {
            throw err;
          })();
          console.log('JSON saved');
          return fs.unlink('strings.csv', function(err) {
            return err && (function() {
              throw err;
            })();
          });
        });
      });
    });
  };

}).call(this);
